# Generated by Django 3.0.2 on 2020-01-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
