# Generated by Django 3.0.2 on 2020-01-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200102_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogos',
            new_name='Jogo',
        ),
    ]
