# Generated by Django 3.0.2 on 2020-01-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200102_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
