# Generated by Django 3.0.2 on 2020-01-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_jogo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to='fotos/%d/%m/%Y'),
        ),
    ]
