# Generated by Django 3.0.2 on 2020-01-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200102_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='categoria',
            field=models.CharField(choices=[('F', 'Futebol'), ('B', 'Basquete'), ('T', 'Tenis')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
